#!/bin/bash

# Made by @andrezoIsHere
# Under the guidance of @dshubenok

# Checking for existing of parameter
if [ "$#" -eq "0" ]; then
	echo "Not enough parameters. You need to enter the name of files which you want to delete as parameters"

else

	# Comment for @dshubenok: Program will parse all parameters as urls and will move them to recycle
	for url in "$@"; do

		# Checking for directory or file
		if [ -d "${url}" ] ; then
			echo "$url is a directory";
		else
			if [ -f "${url}" ]; then
				echo "${url} is a file";
			else
				echo -e "\e[33m${url} \e[39mis not existing file or directory";

			fi
		fi
	done
fi
